export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';
export const MODAL_REGISTRATION_OPEN = 'MODAL_REGISTRATION_OPEN';
export const MODAL_REGISTRATION_CLOSE = 'MODAL_REGISTRATION_CLOSE';
export const MODAL_CART_OPEN = 'MODAL_CART_OPEN';
export const MODAL_CART_CLOSE = 'MODAL_CART_CLOSE';

export const ACCOUNT_AUTH_REQUEST = 'ACCOUNT_AUTH_REQUEST';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REGISTRATION_REQUEST = 'ACCOUNT_REGISTRATION_REQUEST';
export const ACCOUNT_REGISTRATION_SUCCESS = 'ACCOUNT_REGISTRATION_SUCCESS';
export const ACCOUNT_REGISTRATION_FAIL = 'ACCOUNT_REGISTRATION_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const MESSAGE_SHOW = 'MESSAGE_SHOW';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const CATEGORY_SET_ACTIVE = 'CATEGORY_SET_ACTIVE';

export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL';
export const TAG_SET_ACTIVE = 'TAG_SET_ACTIVE';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_SET_SORT = 'PRODCUT_SET_SORT';

export const PRODUCT_PAGE_CHANGE = 'PRODUCT_PAGE_CHANGE';
export const PRODUCT_PAGE_END = 'PRODUCT_PAGE_END';

export const SELECTED_REQUEST = 'SELECTED_REQUEST';
export const SELECTED_SUCCESS = 'SELECTED_SUCCESS';
export const SELECTED_FAIL = 'SELECTED_FAIL';

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT';
export const CART_CLEAR_PRODUCT = 'CART_CLEAR_PRODUCT';

export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL';

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';
