export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';
export const MODAL_REGISTRATION_OPEN = 'MODAL_REGISTRATION_OPEN';
export const MODAL_REGISTRATION_CLOSE = 'MODAL_REGISTRATION_CLOSE';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';
