export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';
export const MODAL_REGISTRATION_OPEN = 'MODAL_REGISTRATION_OPEN';
export const MODAL_REGISTRATION_CLOSE = 'MODAL_REGISTRATION_CLOSE';
export const MODAL_CART_OPEN = 'MODAL_CART_OPEN';
export const MODAL_CART_CLOSE = 'MODAL_CART_CLOSE';

export const ACCOUNT_AUTH_REQUEST = 'ACCOUNT_AUTH_REQUEST';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REGISTRATION_REQUEST = 'ACCOUNT_REGISTRATION_REQUEST';
export const ACCOUNT_REGISTRATION_SUCCESS = 'ACCOUNT_REGISTRATION_SUCCESS';
export const ACCOUNT_REGISTRATION_FAIL = 'ACCOUNT_REGISTRATION_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const MESSAGE_SHOW = 'MESSAGE_SHOW';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_PAGE_CHANGE = 'PRODUCT_PAGE_CHANGE';
export const PRODUCT_PAGE_END = 'PRODUCT_PAGE_END';

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT';
export const CART_CLEAR_PRODUCT = 'CART_CLEAR_PRODUCT';